### PR TITLE
added cut copy paste

### PR DESCRIPTION
**Pull request by hrishikesharma**
I have added the cut, copy, paste feature. also works with shortcut keys(ctrl+x, ctrl+c, ctrl+v)

### CODE REVIEW

**Comment by hrishikesharma** [comment]
Please tell me if anything I can improve.   Actually, I am new to programming😅.

**Comment by SethWalkeroo** [comment]
@hrishikesharma Thanks for the contribution! I am working on something that might really change up the text area atm, so it might be a little longer until I can review and merge this.

**Comment by hrishikesharma** [comment]
@SethWalkeroo  Ok no issues.
If you like my contribution then please label my PR as hacktoberfest-accepted

**Comment by SethWalkeroo** [comment]
@all-contributors please add hrishikesharma  for code

**Pull request merged**
