### PR TITLE
added save file popup

### LINKED ISSUE #6: Create a pop up message that asks the user if they want to save before exiting.
The pop up should either instantly save the file if it already exists, or allow the user to do the "save as" function if it has never been saved before.

### PR DESCRIPTION
**Pull request by aishuo07**
I have added a popup which will appear when we click exit in the menu bar if the file doesn't exist then it will save the file
else it will open save as menu if you select no the editor will be quitted

### CODE REVIEW

**Review by SethWalkeroo — CHANGES_REQUESTED** [review]
Good job at getting it working. Is there a way you can make it match the theme of the editor and make it so the user can drag the window? Also, is it possible to generate the message when the user closes the window by using the exit button e.g. using the exit button on their OS window? If not, that's fine, but those first changes are a must before I merge this.

**Comment by aishuo07** [comment]
Yes i will create a matching theme

**Comment by SethWalkeroo** [comment]
@aish0007 Sorry, someone else solved this issue already. I hope you didn't spend too much time on this.

**Comment by aishuo07** [comment]
no problem

**Pull request closed without merging**
