### PR TITLE
Add autoclosing paranthesis and brackets

### PR DESCRIPTION
**Pull request by Kishore-abhimanyu**
# Add autoclosing paranthesis and brackets

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/SethWalkeroo/Quiet-Text/blob/main/CONTRIBUTING.md)?

- [x] Yes
- [ ] No

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

## Checklist:

- [x] My works and is relatively clean. 
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by SethWalkeroo — CHANGES_REQUESTED** [review]
_tkinter.TclError: bad event type or keysym "{"

I am getting an error. Please fix.

**Comment by Kishore-abhimanyu** [comment]
I dont see any error for this. Can you explain this and attach a screenshot?

**Comment by SethWalkeroo** [comment]
> I dont see any error for this. Can you explain this and attach a screenshot?

I am not sure how you made this work on your machine, but you need to change the bindings for the textarea. <KeyRelease-{> isn't a valid binding. Here is a list of all the different binding commands you can use: https://www.tcl.tk/man/tcl8.4/TkCmd/keysyms.html.

An example of a valid one would be Shift-parenleft or Shift-bracketleft

You also have the function names mixed up. autoclose_brackets autocloses parenthesis and autoclose_parentheses closes brackets in your code. You should change that as well.

**Comment by Kishore-abhimanyu** [comment]
I have added the necessary changes

**Comment by Kishore-abhimanyu** [comment]
can you tell me the reason for closing this PR?

**Pull request closed without merging**
